In [1]:
import statsapi
import pandas as pd
import numpy as np
from datetime import date

In [2]:
# Dates
start_date='07/23/2020'
todays_date = date.today()
output_dir = 'data/'

In [8]:
# # Get team ids -- need them for future queries
# teams = statsapi.get('teams', {
#     'sportIds': 1
# }, force=False)['teams']

# team_lst = []
# for t in teams:
#     team_lst.append({ 
#         'name': t['name'],
#         'id': t['id'] 
#     })
# pd.DataFrame(team_lst).to_csv(output_dir + 'teams.csv', index=False)
team_df = pd.read_csv(output_dir + 'teams.csv')

In [16]:
game_lst = []
for idx, row in team_df.iterrows():
    games = statsapi.schedule(start_date=start_date, end_date=todays_date, team=row['id'], opponent="", sportId=1, game_id=None)
    keys = ['game_id', 'game_date', 'status', 'home_id', 'away_id']
    for g in games:
        subset = {k: g.get(k, None) for k in keys}
        subset['team_name'] = row['name']
        # Determine outcome if game has been played
        if g['status'] == 'Final':
            subset['home_score'] = g['home_score']
            subset['away_score'] = g['away_score']
            subset['win_status'] = 1 if g['winning_team'] == row['name'] else 0
        else:
            subset['home_score'] = np.nan
            subset['away_score'] = np.nan
            subset['win_status'] = np.nan
        game_lst.append(subset)

id                     108
name    Los Angeles Angels
Name: 0, dtype: object
id                       109
name    Arizona Diamondbacks
Name: 1, dtype: object
id                    110
name    Baltimore Orioles
Name: 2, dtype: object
id                 111
name    Boston Red Sox
Name: 3, dtype: object
id               112
name    Chicago Cubs
Name: 4, dtype: object
id                  113
name    Cincinnati Reds
Name: 5, dtype: object
id                    114
name    Cleveland Indians
Name: 6, dtype: object
id                   115
name    Colorado Rockies
Name: 7, dtype: object
id                 116
name    Detroit Tigers
Name: 8, dtype: object
id                 117
name    Houston Astros
Name: 9, dtype: object
id                     118
name    Kansas City Royals
Name: 10, dtype: object
id                      119
name    Los Angeles Dodgers
Name: 11, dtype: object
id                       120
name    Washington Nationals
Name: 12, dtype: object
id                121
name    New York Mets
Name: 13, dtype: object
id                    133
name    Oakland Athletics
Name: 14, dtype: object
id                     134
name    Pittsburgh Pirates
Name: 15, dtype: object
id                   135
name    San Diego Padres
Name: 16, dtype: object
id                   136
name    Seattle Mariners
Name: 17, dtype: object
id                       137
name    San Francisco Giants
Name: 18, dtype: object
id                      138
name    St. Louis Cardinals
Name: 19, dtype: object
id                 139
name    Tampa Bay Rays
Name: 20, dtype: object
id                140
name    Texas Rangers
Name: 21, dtype: object
id                    141
name    Toronto Blue Jays
Name: 22, dtype: object
id                  142
name    Minnesota Twins
Name: 23, dtype: object
id                        143
name    Philadelphia Phillies
Name: 24, dtype: object
id                 144
name    Atlanta Braves
Name: 25, dtype: object
id                    145
name    Chicago White Sox
Name: 26, dtype: object
id                146
name    Miami Marlins
Name: 27, dtype: object
id                   147
name    New York Yankees
Name: 28, dtype: object
id                    158
name    Milwaukee Brewers
Name: 29, dtype: object

In [17]:
pd.DataFrame(game_lst).to_csv(output_dir + str(todays_date) + '.csv', index=False)